# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  name: 'Default'
   
steps:  
- task: NodeTool@0  
  inputs:  
    versionSpec: '12.x'  
  displayName: 'Install Node.js 12.x'  
- task: Npm@1  
  displayName: 'Angular CLI'  
  inputs:  
    command: custom  
    verbose: true  
    customCommand: 'install @angular/cli'  
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: true  
  
- task: Npm@1  
  displayName: Build  
  inputs:  
    command: custom  
    verbose: true  
    customCommand: 'run build'  
  
- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: AdminPanle'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: AdminPanle  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@1
  displayName: 'Download Pipeline Artifact'  
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist' 