steps:
  - task: Npm@0
    displayName: 'npm install'
    inputs:
      arguments: '--force'

  - task: Npm@1
    displayName: 'npm install angular cli'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install @angular/cli'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build-prod'

  - task: ArchiveFiles@1
    displayName: 'Archive files '
    inputs:
      rootFolder: '$(System.DefaultWorkingDirectory)/dist/Gashtineh.AdminPanel' #name of your project on angular.json .defaultProject value
      includeRootFolder: false

  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '$(Build.BuildId).zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'